version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  commands:
    - pip install -r docs/requirements.txt
    - mkdocs build -c -f mkdocs.yml

# Build from the docs/ directory with Sphinx
# sphinx:
#   configuration: docs/conf.py
# mkdocs:
#   configuration: mkdocs.yml

# Explicitly set the version of Python and its requirements
# python:
#   install:
#     - requirements: docs/requirements.txt
